---
- name: Install Scion Coord Software
  apt: name={{ item }}
  with_items:
  - git
  - golang-go
  - python-mysqldb
  - mysql-server

- name: Create MySQL root user
  mysql_user:
    name: root
    password: "{{ mysql_pass }}"
    host: localhost
    login_password: "{{ mysql_pass }}"

- name: Create database
  mysql_db:
    name: "{{ mysql_db }}"
    login_password: "{{ mysql_pass }}"

- name: Make sure GOPATH exists in .profile
  lineinfile: dest=/home/scion/.profile line="export GOPATH=\"$HOME/go\""

- name: Make sure PATH exists in .profile
  lineinfile: dest=/home/scion/.profile line="export PATH=\"$HOME/.local/bin:$GOPATH/bin:$PATH\""

- name: Make sure alias for SCION Coordination Service folder exists .profile
  lineinfile: dest=/home/scion/.profile
              line="alias cdscioncoord='cd {{ repo_location }}'"

- name: Make sure SCION Coordination Service folder exists
  file: path={{ repo_location }} state=directory
  become_user: scion

- name: Checkout SCION Coord codebase
  git: repo=https://github.com/chaehni/scion-coord
       dest={{ repo_location }}
       version={{ scion_coord_version }}
       force=yes
  become_user: scion

- name: Set correct bind host for Coordination Service
  replace:
    path: "{{ repo_location }}/conf/development.conf"
    regexp: http.bind_address = "[A-Za-z0-9.-]+"
    replace: http.bind_address = "{{ coord_bind_address }}"

- name: Set correct bind port for Coordination Service
  replace:
    path: "{{ repo_location }}/conf/development.conf"
    regexp: http.bind_port = "[0-9]+"
    replace: http.bind_port = "{{ coord_bind_port }}"

- name: Set correct address for Coordination Service
  replace:
    path: "{{ repo_location }}/conf/development.conf"
    regexp: http.host_address = "[A-Za-z0-9.-]+"
    replace: http.host_address = "{{ coord_address }}"

- name: Set Postmark server token
  replace:
    path: "{{ repo_location }}/conf/development.conf"
    regexp: email.pm_server_token = ""
    replace: email.pm_server_token = "{{ pm_server_token }}"

- name: Set Postmark account token
  replace:
    path: "{{ repo_location }}/conf/development.conf"
    regexp: email.pm_account_token = ""
    replace: email.pm_server_token = "{{ pm_account_token }}"

- name: Set captcha site key
  replace:
    path: "{{ repo_location }}/conf/development.conf"
    regexp: captcha.site_key = ""
    replace: captcha.site_key = "{{ captcha.site_key }}"

- name: Set captcha secret key
  replace:
    path: "{{ repo_location }}/conf/development.conf"
    regexp: captcha.secret_key = ""
    replace: captcha.secret_key = "{{ captcha.secret_key }}"

- name: Install govendor
  shell: . /home/scion/.profile && go get github.com/kardianos/govendor
  args:
    creates: /home/scion/go/src/github.com/kardianos
    chdir: "{{ repo_location }}/vendor"
  become_user: scion

- name: Do govendor sync
  shell: ". /home/scion/.profile && govendor sync"
  args:
     creates: "{{ repo_location }}/vendor/github.com"
     chdir: "{{ repo_location }}/vendor"
  become_user: scion