---
- name: Add scion user
  user:
    name: scion
    comment: "SCION user"
    groups: sudo
    shell: /bin/bash

- name: Install the scion sudoers file under /etc/sudoers.d/scion
  copy:
    src: files/scion_sudoers
    dest: /etc/sudoers.d/scion
    owner: root
    group: root

- name: Create ~scion/.ssh and ensure permissions=0700
  file:
    path: ~scion/.ssh
    state: directory
    owner: scion
    group: scion
    mode: 0700

- name: Setup ~scion/.ssh/authorized_keys and ensure permissions=0600
  copy:
    src: files/authorized_keys-scion
    dest: ~scion/.ssh/authorized_keys
    owner: scion
    group: scion
    mode: 0600


